/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyy_newtest_jni_JniTest */

#ifndef _Included_com_dyy_newtest_jni_JniTest
#define _Included_com_dyy_newtest_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dyy_newtest_jni_JniTest
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyy_newtest_jni_JniTest_getJniString
  (JNIEnv *, jclass);

/*
 * Class:     com_dyy_newtest_jni_JniTest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_dyy_newtest_jni_JniTest_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
