/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyy_newtest_jni_AesUtils */

#ifndef _Included_com_dyy_newtest_jni_AesUtils
#define _Included_com_dyy_newtest_jni_AesUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dyy_newtest_jni_AesUtils
 * Method:    getAesEncContent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyy_newtest_jni_AesUtils_getAesEncContent
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_dyy_newtest_jni_AesUtils
 * Method:    getAesDecContent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyy_newtest_jni_AesUtils_getAesDecContent
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
