/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyy_newtest_jni_AesUtils */

#ifndef _Included_com_dyy_newtest_jni_AesUtils
#define _Included_com_dyy_newtest_jni_AesUtils
#ifdef __cplusplus
extern "C" {
#endif
const char *AES_KEY = "55C63C2A5D572C4CF638C82105C9905C";
/*
 * Class:     com_dyy_newtest_jni_AesUtils
 * Method:    getAesEncContent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyy_newtest_jni_AesUtils_getAesEncContent
        (JNIEnv *env, jclass jclass1, jstring str){
        jclass clazz=NULL;
        jmethodID mid;
        jstring aesKey=NULL;
        jstring result=NULL;
        if (str==NULL){
            return NULL;
        }
        //1.找到AesUtils类,并返回该类的class对象；
        clazz=(*env)->FindClass(env,"com/dyy/newtest/jni/AesUtils");
        //2.找到AesUtils类中的加密方法
        mid=(*env)->GetStaticMethodID(env,clazz,"encrypt","(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
        if (mid==NULL){
            (*env)->DeleteLocalRef(env,clazz);
            return NULL;
        }
        aesKey=(*env)->NewStringUTF(env, AES_KEY);
        //3.调用AesUtils类中的加密方法
        result = (*env)->CallStaticObjectMethod(env, clazz, mid, str, aesKey);
        //4.删除局部引用
        (*env)->DeleteLocalRef(env,clazz);
        return result;
     }

/*
 * Class:     com_dyy_newtest_jni_AesUtils
 * Method:    getAesDecContent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyy_newtest_jni_AesUtils_getAesDecContent
        (JNIEnv *env, jclass jclass1, jstring str){
        if (str==NULL){
            return NULL;
        }
        jstring result=NULL;
        jstring aesKey=NULL;
        jmethodID mid;
        jclass clazz=NULL;
        //1.找到AesUtils类，并返回该类的class对象；
        clazz=(*env)->FindClass(env,"com/dyy/newtest/jni/AesUtils");
        aesKey=(*env)->NewStringUTF(env,AES_KEY);
        //2.找到AesUtils类中的解密方法
        mid=(*env)->GetStaticMethodID(env,clazz,"decrypt","(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
        if (mid==NULL){
            (*env)->DeleteLocalRef(env,clazz);
            return NULL;
        }
        //3.调用AesUtils类中的解密方法
        result=(*env)->CallStaticObjectMethod(env,clazz,mid,str,aesKey);
        //4.删除局部引用
        (*env)->DeleteLocalRef(env,clazz);
        return result;
}

#ifdef __cplusplus
}
#endif
#endif
